import base64
import os
import sys
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import quote

import requests

_GH_BODY_LIMIT = 65000

_default_branch_cache: Optional[str] = None


def dedupe_marker(nodeid: str) -> str:
    """Stable marker embedded in issue bodies for duplicate detection."""
    return f"<!-- dedupe:{nodeid} -->"


def format_issue(
    test_name: str,
    nodeid: str,
    summary: str,
    error_text: str,
    screenshot_url: Optional[str] = None,
) -> str:
    """
    Build Markdown for a failed test issue. ``summary`` is caller-provided (e.g. from AI).
    Appends a hidden dedupe marker so open issues can be matched without relying on title text.
    """
    text = (error_text or "").strip()
    if len(text) > _GH_BODY_LIMIT:
        text = text[: _GH_BODY_LIMIT - 80] + "\n\n…(truncated for GitHub body size limit)"

    shot = ""
    if screenshot_url:
        shot = f"""
### 📸 Screenshot
![failure screenshot]({screenshot_url})
"""

    return f"""## ❌ Test Failure: {test_name}

### 📌 Summary
{summary}

### 🧪 Test Details
- Test Name: {test_name}
- Type: UI
- Status: Failed
{shot}
### 💥 Error
```
{text}
```

---
Generated by AutoDefectAI 🤖

{dedupe_marker(nodeid)}
"""


def get_default_branch() -> str:
    """Resolve default branch (env or GitHub API)."""
    global _default_branch_cache
    env = os.getenv("GITHUB_DEFAULT_BRANCH", "").strip()
    if env:
        return env
    if _default_branch_cache:
        return _default_branch_cache
    token = os.getenv("GITHUB_TOKEN", "").strip()
    repo = os.getenv("GITHUB_REPO", "").strip()
    if not token or not repo:
        return "main"
    url = f"https://api.github.com/repos/{repo}"
    r = requests.get(
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
        },
        timeout=30,
    )
    if r.status_code != 200:
        return "main"
    _default_branch_cache = r.json().get("default_branch") or "main"
    return _default_branch_cache


def upload_png_to_repo(content: bytes, remote_path: str) -> str:
    """
    Commit a PNG into the repo via Contents API and return a URL usable in Markdown.

    Requires a token with **contents: write** (classic: ``repo`` scope).
    """
    token = os.getenv("GITHUB_TOKEN", "").strip()
    repo = os.getenv("GITHUB_REPO", "").strip()
    if not token or not repo:
        raise ValueError("GITHUB_TOKEN and GITHUB_REPO must be set")

    branch = get_default_branch()
    url = f"https://api.github.com/repos/{repo}/contents/{remote_path}"
    message = f"AutoDefectAI screenshot {datetime.now(timezone.utc).isoformat()}"
    body = {
        "message": message,
        "content": base64.b64encode(content).decode("ascii"),
        "branch": branch,
    }
    r = requests.put(
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
        },
        json=body,
        timeout=120,
    )
    r.raise_for_status()
    data = r.json()
    dl = (data.get("content") or {}).get("download_url")
    if dl:
        return dl
    owner, name = repo.split("/", 1)
    encoded = "/".join(quote(seg, safe="") for seg in remote_path.split("/"))
    return f"https://raw.githubusercontent.com/{owner}/{name}/{branch}/{encoded}"


def create_issue(title: str, body: str) -> requests.Response:
    token = os.getenv("GITHUB_TOKEN", "").strip()
    repo = os.getenv("GITHUB_REPO", "").strip()

    if not token or not repo:
        raise SystemExit(
            "Set GITHUB_TOKEN and GITHUB_REPO environment variables."
        )

    url = f"https://api.github.com/repos/{repo}/issues"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }

    data = {
        "title": title,
        "body": body,
        "labels": ["bug", "automation"]   # optional but recommended
    }

    return requests.post(url, json=data, headers=headers, timeout=30)


def issue_exists(title: str) -> bool:
    """Legacy: open issue with exact title match (first API page only)."""
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")

    url = f"https://api.github.com/repos/{repo}/issues"
    headers = {"Authorization": f"Bearer {token}"}

    response = requests.get(url, headers=headers, timeout=30)

    if response.status_code != 200:
        return False

    issues = response.json()

    for issue in issues:
        if issue["title"] == title and issue["state"] == "open":
            return True

    return False


def issue_exists_for_nodeid(nodeid: str) -> bool:
    """
    True if an open issue already exists for this test (body dedupe marker or legacy title).
    Use this when issue titles are AI-generated and vary between runs.
    """
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")

    url = f"https://api.github.com/repos/{repo}/issues"
    headers = {"Authorization": f"Bearer {token}"}

    response = requests.get(url, headers=headers, timeout=30)

    if response.status_code != 200:
        return False

    marker = dedupe_marker(nodeid)
    legacy_title = f"Failed: {nodeid}"

    for issue in response.json():
        if issue.get("state") != "open":
            continue
        if issue.get("title") == legacy_title:
            return True
        body = issue.get("body") or ""
        if marker in body:
            return True

    return False


def main():
    title = sys.argv[1] if len(sys.argv) > 1 else "Test issue"
    body = sys.argv[2] if len(sys.argv) > 2 else "Body"

    r = create_issue(title, body)

    issue_url = r.json().get("html_url")
    print(f"🚀 Issue created: {issue_url}")

    r.raise_for_status()


if __name__ == "__main__":
    main()